name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Node.js environment
        uses: actions/setup-node@v4.1.0

      - name: Checkout head
        uses: actions/checkout@v4
        with:
          path: head

      - name: Checkout base ref
        uses: actions/checkout@v4
        with:
          path: base
          ref: ${{ github.event.pull_request.base.sha || 'main' }}

      - name: Verify breaking changes
        uses: bufbuild/buf-action@v1
        with:
          input: head
          breaking_against: base
          format: true
          lint: true
          pr_comment: true
