name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Node.js environment
        uses: actions/setup-node@v4.1.0
        
      - uses: actions/checkout@v4
    
      - name: NPM Install
        run: npm install

      - name: Verify breaking changes on protobufs
        run: npm run verify-protos
